FROM ghcr.io/astral-sh/uv:0.11.2 AS uv
FROM public.ecr.aws/lambda/python:3.12

COPY --from=uv /uv /uvx /bin/

# Set working directory to Lambda task root
WORKDIR ${LAMBDA_TASK_ROOT}

# Install dependencies using uv
COPY pyproject.toml uv.lock README.md ./
RUN uv export --frozen --no-dev --format requirements-txt > requirements.txt && \
    uv pip install -r requirements.txt --target ${LAMBDA_TASK_ROOT}

# Copy the rest of the application
COPY src ./src

# Set the CMD to your handler
CMD ["src.api.main.handler"]
